package publisher

import (
	"fmt"
	"ohman/src/core/taxonomy"
	"ohman/src/core/textutil"
	"sort"
	"strings"
	"time"

	storage "ohman/src/core/db"
	ght "ohman/src/core/github"
)

func (p *Publisher) buildFindingsReadme(repos []*ght.RepoData) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Ohman Explorer\n\n")
	fmt.Fprintf(&sb, "Autonomous GitHub project discovery and comparison index.\n\n")
	fmt.Fprintf(&sb, "Last updated: %s\n\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(&sb, "Total indexed projects: %d\n\n", len(repos))
	fmt.Fprintf(&sb, "## Disclaimer\n\n")
	fmt.Fprintf(&sb, "This library is AI-assisted curation, not a final endorsement. Scores are signals for discovery and comparison. Repo age, activity, maintenance history, and direct inspection should be considered before adoption, especially for young projects.\n\n")
	fmt.Fprintf(&sb, "## Categories\n\n")

	groups := groupByCategory(repos)
	fmt.Fprintf(&sb, "| Category | Projects |\n")
	fmt.Fprintf(&sb, "|---|---:|\n")
	for _, category := range sortedCategories(groups) {
		fmt.Fprintf(&sb, "| [%s](categories/%s.md) | %d |\n", category, category, len(groups[category]))
	}

	languages := groupByLanguage(repos)
	if len(languages) > 0 {
		fmt.Fprintf(&sb, "\n## Languages\n\n")
		fmt.Fprintf(&sb, "| Language | Projects |\n")
		fmt.Fprintf(&sb, "|---|---:|\n")
		for _, language := range sortedLanguages(languages) {
			fmt.Fprintf(&sb, "| %s | %d |\n", language, languages[language])
		}
	}

	fmt.Fprintf(&sb, "\n## Data\n\n")
	fmt.Fprintf(&sb, "- [Machine-readable repo data](data/repos.json)\n")
	fmt.Fprintf(&sb, "- [Current library snapshot](findings/%s.md)\n\n", time.Now().Format("2006-01-02"))
	fmt.Fprintf(&sb, "Repository details live inside the category pages.\n\n")
	fmt.Fprintf(&sb, "Managed by Ohman Explorer.\n")
	return sb.String()
}

func (p *Publisher) buildFindingsArchive(repos []*ght.RepoData) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Library Snapshot %s\n\n", time.Now().Format("2006-01-02"))
	fmt.Fprintf(&sb, "Total indexed projects: %d\n\n", len(repos))
	fmt.Fprintf(&sb, "AI scores are discovery signals. Repo age and recent activity should be checked before adoption.\n\n")
	for i, repo := range repos {
		writeRepoCard(&sb, i+1, repo)
	}
	return sb.String()
}

func (p *Publisher) buildCategoryPage(category string, repos []*ght.RepoData) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s\n\n", category)
	fmt.Fprintf(&sb, "Curated projects in this category.\n\n")
	fmt.Fprintf(&sb, "Note: young repositories can show strong potential but still carry higher stability and maintenance risk.\n\n")
	for i, repo := range repos {
		writeRepoCard(&sb, i+1, repo)
	}
	return sb.String()
}

func (p *Publisher) buildReadme(repos []*storage.RepoData) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Ohman Explorer - Discovery List\n\n")
	fmt.Fprintf(&sb, "Repository yang dikunjungi secara otonom oleh Ohman bot.\n\n")
	fmt.Fprintf(&sb, "**Total repos visited:** %d\n\n", len(repos))
	fmt.Fprintf(&sb, "**Last updated:** %s\n\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC"))

	langs := make(map[string]int)
	totalStars := 0
	for _, r := range repos {
		langs[r.Language]++
		totalStars += r.Stars
	}
	fmt.Fprintf(&sb, "## Stats\n\n")
	fmt.Fprintf(&sb, "- Total stars collected: %d\n", totalStars)
	fmt.Fprintf(&sb, "- Languages discovered:\n")
	for lang, count := range langs {
		if lang != "" {
			fmt.Fprintf(&sb, "  - %s: %d repos\n", lang, count)
		}
	}
	fmt.Fprintf(&sb, "\n---\n\n")

	fmt.Fprintf(&sb, "## Discovered Repositories\n\n")
	fmt.Fprintf(&sb, "| # | Repository | Description | Stars | Language | Score |\n")
	fmt.Fprintf(&sb, "|---|------------|-------------|-------|----------|-------|\n")

	for i, r := range repos {
		desc := r.Description
		if len(desc) > 80 {
			desc = desc[:77] + "..."
		}
		desc = strings.ReplaceAll(desc, "|", "\\|")
		lang := r.Language
		if lang == "" {
			lang = "-"
		}
		fmt.Fprintf(&sb, "| %d | [%s](https://github.com/%s) | %s | %d | %s | %.1f |\n",
			i+1, r.FullName, r.FullName, desc, r.Stars, lang, r.AIScore)
	}

	fmt.Fprintf(&sb, "\n---\n*Generated by Ohman Explorer Bot*\n")
	return sb.String()
}

func (p *Publisher) buildDailyLog(repos []*storage.RepoData) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Exploration Log - %s\n\n", time.Now().Format("2006-01-02"))
	fmt.Fprintf(&sb, "**Repos discovered today:** %d\n\n", len(repos))

	sort.Slice(repos, func(i, j int) bool {
		return repos[i].AIScore > repos[j].AIScore
	})

	fmt.Fprintf(&sb, "## Top Discoveries\n\n")
	limit := min(len(repos), 10)
	for i := range limit {
		r := repos[i]
		fmt.Fprintf(&sb, "### %d. [%s](https://github.com/%s) - stars: %d\n\n",
			i+1, r.FullName, r.FullName, r.Stars)
		if r.Description != "" {
			fmt.Fprintf(&sb, "> %s\n\n", r.Description)
		}
		if r.AINotes != "" {
			fmt.Fprintf(&sb, "**AI Notes:** %s\n\n", truncate(r.AINotes, 200))
		}
		if r.ReadmeSummary != "" {
			fmt.Fprintf(&sb, "**Summary:** %s\n\n", r.ReadmeSummary)
		}
		fmt.Fprintf(&sb, "- Language: %s\n", orDefault(r.Language, "unknown"))
		fmt.Fprintf(&sb, "- Topics: %s\n", strings.Join(r.Topics, ", "))
		fmt.Fprintf(&sb, "- AI Score: %.1f/10\n\n", r.AIScore)
		fmt.Fprintf(&sb, "---\n\n")
	}

	fmt.Fprintf(&sb, "*Generated by Ohman Explorer Bot*\n")
	return sb.String()
}

type repoBuilderHelpers struct{}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func shortDescription(repo *ght.RepoData) string {
	text := textutil.NormalizeText(repo.ReadmeSummary)
	if text == "" {
		text = textutil.NormalizeText(repo.Description)
	}
	if text == "" {
		text = "No description available."
	}
	text = strings.ReplaceAll(text, "\n", " ")
	text = strings.Join(strings.Fields(text), " ")
	return truncate(text, 220)
}

func writeRepoCard(sb *strings.Builder, index int, repo *ght.RepoData) {
	fmt.Fprintf(sb, "### %d. %s\n\n", index, repo.FullName)
	fmt.Fprintf(sb, "- Link: https://github.com/%s\n", repo.FullName)
	fmt.Fprintf(sb, "- Title: %s\n", repo.FullName)
	fmt.Fprintf(sb, "- Description: %s\n", shortDescription(repo))
	fmt.Fprintf(sb, "- Category: %s\n", categoryName(repo))
	if repo.ProjectType != "" {
		fmt.Fprintf(sb, "- Type: %s\n", repo.ProjectType)
	}
	if repo.Language != "" {
		fmt.Fprintf(sb, "- Language: %s\n", repo.Language)
	}
	fmt.Fprintf(sb, "- Created: %s\n", formatRepoDate(repo.CreatedAt))
	fmt.Fprintf(sb, "- Age: %s\n", repoAgeLabel(repo))
	fmt.Fprintf(sb, "- Last pushed: %s\n", formatRepoDate(repo.PushedAt))
	fmt.Fprintf(sb, "- Assessment context: %s\n", repoAssessmentContext(repo))
	fmt.Fprintf(sb, "- Score: %.1f/10\n", repo.AIScore)
	fmt.Fprintf(sb, "- Novelty: %.1f/10\n", repo.Novelty)
	fmt.Fprintf(sb, "- Maturity: %.1f/10\n", repo.Maturity)
	fmt.Fprintf(sb, "- Small repo potential: %.1f/10\n", repo.SmallRepoFit)
	if repo.Stars > 0 {
		fmt.Fprintf(sb, "- Stars: %d\n", repo.Stars)
	}
	if repo.AINotes != "" {
		fmt.Fprintf(sb, "- Reason: %s\n", textutil.NormalizeText(repo.AINotes))
	}
	if len(repo.Strengths) > 0 {
		fmt.Fprintf(sb, "- Strengths:\n")
		for _, item := range repo.Strengths {
			fmt.Fprintf(sb, "  - %s\n", textutil.NormalizeText(item))
		}
	}
	if len(repo.Weaknesses) > 0 {
		fmt.Fprintf(sb, "- Weaknesses:\n")
		for _, item := range repo.Weaknesses {
			fmt.Fprintf(sb, "  - %s\n", textutil.NormalizeText(item))
		}
	}
	fmt.Fprintf(sb, "\n")
}

func groupByCategory(repos []*ght.RepoData) map[string][]*ght.RepoData {
	groups := map[string][]*ght.RepoData{}
	for _, repo := range repos {
		category := categoryName(repo)
		groups[category] = append(groups[category], repo)
	}
	return groups
}

func sortedCategories(groups map[string][]*ght.RepoData) []string {
	categories := make([]string, 0, len(groups))
	for category := range groups {
		categories = append(categories, category)
	}
	sort.Strings(categories)
	return categories
}

func groupByLanguage(repos []*ght.RepoData) map[string]int {
	groups := map[string]int{}
	for _, repo := range repos {
		language := strings.TrimSpace(repo.Language)
		if language == "" {
			language = "Unknown"
		}
		groups[language]++
	}
	return groups
}

func sortedLanguages(groups map[string]int) []string {
	languages := make([]string, 0, len(groups))
	for language := range groups {
		languages = append(languages, language)
	}
	sort.Slice(languages, func(i, j int) bool {
		if groups[languages[i]] != groups[languages[j]] {
			return groups[languages[i]] > groups[languages[j]]
		}
		return languages[i] < languages[j]
	})
	return languages
}

func categoryName(repo *ght.RepoData) string {
	return taxonomy.NormalizeCategory(repo.Category)
}

func repoAge(createdAt time.Time, now time.Time) (int, string) {
	if createdAt.IsZero() {
		return 0, "unknown"
	}
	if now.IsZero() {
		now = time.Now().UTC()
	}
	if createdAt.After(now) {
		return 0, "0 days"
	}
	days := int(now.Sub(createdAt).Hours() / 24)
	return days, formatAgeDays(days)
}

func repoAgeLabel(repo *ght.RepoData) string {
	if repo == nil {
		return "unknown"
	}
	if repo.RepoAgeLabel != "" {
		return repo.RepoAgeLabel
	}
	_, label := repoAge(repo.CreatedAt, time.Now().UTC())
	return label
}

func repoAssessmentContext(repo *ght.RepoData) string {
	if repo == nil || repo.CreatedAt.IsZero() {
		return "age data is unavailable, so maturity should be verified manually"
	}
	days, _ := repoAge(repo.CreatedAt, time.Now().UTC())
	switch {
	case days < 30:
		return "very young repo; promising signals need extra validation"
	case days < 180:
		return "young repo; potential is meaningful but stability is still forming"
	case days < 730:
		return "established enough for stronger comparison, but maintenance trend still matters"
	default:
		return "older repo; long-term activity and recent maintenance matter more than age alone"
	}
}

func formatAgeDays(days int) string {
	switch {
	case days < 0:
		return "unknown"
	case days < 30:
		return fmt.Sprintf("%d days", days)
	case days < 365:
		months := max(1, days/30)
		return fmt.Sprintf("%d months", months)
	default:
		years := days / 365
		remainingMonths := (days % 365) / 30
		if remainingMonths > 0 {
			return fmt.Sprintf("%d years %d months", years, remainingMonths)
		}
		return fmt.Sprintf("%d years", years)
	}
}

func formatRepoDate(value time.Time) string {
	if value.IsZero() {
		return "unknown"
	}
	return value.UTC().Format("2006-01-02")
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
